package com.orderService.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RestController;

import com.orderService.domain.Order;
import com.orderService.domain.OrderLineItems;
import com.orderService.domain.OrderRequest;
import com.orderService.service.OrderService;

import io.github.resilience4j.circuitbreaker.annotation.CircuitBreaker;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;


@RestController
@RequestMapping("/order")
public class OrderController {
	
	@Autowired
	OrderService orderService;
	
	@PostMapping
	@ResponseStatus(HttpStatus.CREATED)
	@CircuitBreaker(name="inventory", fallbackMethod = "fallbackPlaceOrder")
	public String placeOrder(@RequestBody OrderRequest orderRequest) {
		
		try{
			orderService.placeOrder(orderRequest);
			return "Your order is placed succesfully.";
		}catch(Exception ex) {
			return ex.getMessage();
		}
		
	}
	
	public String fallbackPlaceOrder(OrderRequest orderRequest,RuntimeException runtimeException) {
		System.out.println("+++++++++++fallback method called+++++++++++++++++");
		return "Something went wrong, Please try again later.";
	}
	

}
